-- MySQL Script generated by MySQL Workbench
-- Tue Jan  5 11:24:11 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema one
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema one
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `one` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `one`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `one`.`user` (
  `userEmail` VARCHAR(45) NOT NULL,
  `userPw` VARCHAR(25) NOT NULL,
  `userName` VARCHAR(10) NULL DEFAULT NULL,
  `userTel` VARCHAR(15) NULL DEFAULT NULL,
  `insertDate` DATE NULL DEFAULT NULL,
  `deleteDate` DATE NULL DEFAULT NULL,
  `userGender` VARCHAR(10) NULL,
  `userType` VARCHAR(10) NULL,
  `userInterest` VARCHAR(15) NULL,
  PRIMARY KEY (`userEmail`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `one`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `one`.`product` (
  `ctgType` VARCHAR(25) NOT NULL,
  `prdNo` INT(11) NOT NULL AUTO_INCREMENT,
  `prdName` VARCHAR(45) NOT NULL,
  `prdPrice` VARCHAR(45) NOT NULL,
  `prdStock` VARCHAR(45) NOT NULL,
  `prdContent` TEXT NULL DEFAULT NULL,
  `prdFilename` VARCHAR(45) NULL DEFAULT NULL,
  `prdDFilename` VARCHAR(45) NULL DEFAULT NULL,
  `prdAFilename` VARCHAR(45) NULL DEFAULT NULL,
  `prdGender` VARCHAR(10) NULL,
  `prdType` VARCHAR(10) NULL,
  `prdInterest` VARCHAR(15) NULL,
  PRIMARY KEY (`prdNo`),
  UNIQUE INDEX `prdNo_UNIQUE` (`prdNo` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 41
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`like` (
  `likeNo` INT NOT NULL AUTO_INCREMENT,
  `user_userEmail` VARCHAR(45) NOT NULL,
  `product_prdNo` INT(11) NOT NULL,
  INDEX `fk_like_user_idx` (`user_userEmail` ASC) VISIBLE,
  INDEX `fk_like_product1_idx` (`product_prdNo` ASC) VISIBLE,
  PRIMARY KEY (`likeNo`),
  UNIQUE INDEX `likeNo_UNIQUE` (`likeNo` ASC) VISIBLE,
  CONSTRAINT `fk_like_user`
    FOREIGN KEY (`user_userEmail`)
    REFERENCES `one`.`user` (`userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_like_product1`
    FOREIGN KEY (`product_prdNo`)
    REFERENCES `one`.`product` (`prdNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `one` ;

-- -----------------------------------------------------
-- Table `one`.`cartinfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `one`.`cartinfo` (
  `cartNo` INT(11) NOT NULL AUTO_INCREMENT,
  `user_userId` VARCHAR(15) NOT NULL,
  `cartDate` DATETIME NULL DEFAULT NULL,
  `cartTotalPrice` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`cartNo`, `user_userId`),
  INDEX `fk_orderinfo_user2_idx` (`user_userId` ASC) VISIBLE,
  CONSTRAINT `fk_orderinfo_user20`
    FOREIGN KEY (`user_userId`)
    REFERENCES `one`.`user` (`userEmail`))
ENGINE = InnoDB
AUTO_INCREMENT = 61
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `one`.`cartdetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `one`.`cartdetail` (
  `cartQty` INT(11) NULL DEFAULT NULL,
  `goods_prdNo` INT(11) NOT NULL,
  `user_userId` VARCHAR(15) NOT NULL,
  `DcartNo` INT(11) NOT NULL AUTO_INCREMENT,
  `cartinfo_cartNo` INT(11) NOT NULL,
  PRIMARY KEY (`DcartNo`),
  INDEX `goods_prdNo` (`goods_prdNo` ASC) VISIBLE,
  INDEX `user_userId` (`user_userId` ASC) VISIBLE,
  INDEX `fk_orderdetail_copy1_cartinfo1_idx` (`cartinfo_cartNo` ASC) VISIBLE,
  CONSTRAINT `fk_orderdetail_copy1_cartinfo1`
    FOREIGN KEY (`cartinfo_cartNo`)
    REFERENCES `one`.`cartinfo` (`cartNo`),
  CONSTRAINT `orderdetail_ibfk_20`
    FOREIGN KEY (`goods_prdNo`)
    REFERENCES `one`.`product` (`prdNo`),
  CONSTRAINT `orderdetail_ibfk_30`
    FOREIGN KEY (`user_userId`)
    REFERENCES `one`.`user` (`userEmail`))
ENGINE = InnoDB
AUTO_INCREMENT = 194
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `one`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `one`.`event` (
  `eSeqno` INT(11) NOT NULL AUTO_INCREMENT,
  `eTitle` VARCHAR(45) NULL DEFAULT NULL,
  `eContent` VARCHAR(45) NULL DEFAULT NULL,
  `eFilename` VARCHAR(45) NULL DEFAULT NULL,
  `startDate` DATE NULL DEFAULT NULL,
  `endDate` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`eSeqno`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `one`.`management`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `one`.`management` (
  `goods_prdNo` INT(11) NOT NULL,
  `admin_adminId` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`goods_prdNo`, `admin_adminId`),
  CONSTRAINT `fk_management_goods1`
    FOREIGN KEY (`goods_prdNo`)
    REFERENCES `one`.`product` (`prdNo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `one`.`open`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `one`.`open` (
  `admin_adminId` VARCHAR(15) NOT NULL,
  `event_eSeqno` INT(11) NOT NULL,
  INDEX `fk_open_admin1_idx` (`admin_adminId` ASC) VISIBLE,
  INDEX `open_ibfk_1` (`event_eSeqno` ASC) VISIBLE,
  CONSTRAINT `open_ibfk_1`
    FOREIGN KEY (`event_eSeqno`)
    REFERENCES `one`.`event` (`eSeqno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `one`.`orderinfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `one`.`orderinfo` (
  `ordNo` INT(11) NOT NULL AUTO_INCREMENT,
  `user_userId` VARCHAR(15) NOT NULL,
  `ordDate` DATETIME NULL DEFAULT NULL,
  `ordReceiver` VARCHAR(15) NULL DEFAULT NULL,
  `ordRcvAddress` VARCHAR(45) NULL DEFAULT NULL,
  `ordRcvPhone` VARCHAR(45) NULL DEFAULT NULL,
  `ordPay` VARCHAR(45) NULL DEFAULT NULL,
  `ordBank` VARCHAR(25) NULL DEFAULT NULL,
  `ordCardNo` VARCHAR(20) NULL DEFAULT NULL,
  `ordCardPass` VARCHAR(10) NULL DEFAULT NULL,
  `ordDelivery` VARCHAR(45) NULL DEFAULT '상품 준비중',
  `ordDeliveryDate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ordNo`, `user_userId`),
  INDEX `fk_orderinfo_user2_idx` (`user_userId` ASC) VISIBLE,
  CONSTRAINT `fk_orderinfo_user2`
    FOREIGN KEY (`user_userId`)
    REFERENCES `one`.`user` (`userEmail`))
ENGINE = InnoDB
AUTO_INCREMENT = 112
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `one`.`orderdetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `one`.`orderdetail` (
  `ordQty` INT(11) NULL DEFAULT NULL,
  `ordReview` TEXT NULL DEFAULT NULL,
  `ordStar` VARCHAR(45) NULL DEFAULT NULL,
  `orderinfo_ordNo` INT(11) NOT NULL,
  `goods_prdNo` INT(11) NOT NULL,
  `user_userId` VARCHAR(15) NOT NULL,
  `ordRefund` DATETIME NULL DEFAULT NULL,
  `orddeNo` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`orddeNo`),
  INDEX `fk_orderdetail_orderinfo1_idx` (`orderinfo_ordNo` ASC) VISIBLE,
  INDEX `goods_prdNo` (`goods_prdNo` ASC) VISIBLE,
  INDEX `user_userId` (`user_userId` ASC) VISIBLE,
  CONSTRAINT `orderdetail_ibfk_1`
    FOREIGN KEY (`orderinfo_ordNo`)
    REFERENCES `one`.`orderinfo` (`ordNo`),
  CONSTRAINT `orderdetail_ibfk_2`
    FOREIGN KEY (`goods_prdNo`)
    REFERENCES `one`.`product` (`prdNo`),
  CONSTRAINT `orderdetail_ibfk_3`
    FOREIGN KEY (`user_userId`)
    REFERENCES `one`.`user` (`userEmail`))
ENGINE = InnoDB
AUTO_INCREMENT = 148
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `one`.`participate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `one`.`participate` (
  `user_userId` VARCHAR(15) NOT NULL,
  `win` VARCHAR(45) NULL DEFAULT 'X',
  `event_eSeqno` INT(11) NOT NULL,
  PRIMARY KEY (`user_userId`, `event_eSeqno`),
  INDEX `participate_ibfk_1` (`event_eSeqno` ASC) VISIBLE,
  CONSTRAINT `fk_participate_user1`
    FOREIGN KEY (`user_userId`)
    REFERENCES `one`.`user` (`userEmail`),
  CONSTRAINT `participate_ibfk_1`
    FOREIGN KEY (`event_eSeqno`)
    REFERENCES `one`.`event` (`eSeqno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
